language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: hhvm

services:
    - mysql

before_install:
   - mysql -e "create database IF NOT EXISTS naijaEmoji;" -uroot

   - mysql -e "use database naijaEmoji;" 

   - mysql -e "CREATE TABLE keywords
      (
      id int NOT NULL PRIMARY KEY,
      fullname varchar(255) NOT NULL,
      username varchar(255),
      keyword_name varchar(255),
      password varchar(255),
      updated_at varchar(255)
      );"

   - mysql -e "CREATE TABLE users
      (
      id int NOT NULL PRIMARY KEY,
      emoji_id varchar(255) NOT NULL,
      FirstName varchar(255),
      keyword_name varchar(255),
      created_at varchar(255),
      created_at varchar(255),
      updated_at varchar(255)
      );"  

   - mysql -e "CREATE TABLE emojis
      (
      Id int NOT NULL PRIMARY KEY,
      name varchar(255) NOT NULL,
      FirstName varchar(255),
      chars varchar(255),
      created_by varchar(255),
      category varchar(255),
      created_at varchar(255),
      updated_at varchar(255)
      );"  


before_script:
   - mysql -e "create database IF NOT EXISTS naijaEmoji;"

install: travis_retry composer install --no-interaction --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - phpunit --coverage-text --coverage-clover=coverage.clover
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
  - travis_retry php vendor/bin/coveralls -v